version: "3"

services:
  vecno_explorer:
    container_name: vecno_explorer
    image: supertypo/vecnoexplorer:latest
    restart: unless-stopped
    environment:
      API_URI: "http://localhost:8000"
      API_WS_URI: "ws://localhost:8000"
    ports:
      - "8080:8080/tcp"

  vecno_rest_server:
    container_name: vecno_rest_server
    image: supertypo/vecnorest-server:latest
    restart: unless-stopped
    environment:
      VECNOD_HOST_1: vecnod:16110
      SQL_URI: postgresql+asyncpg://postgres:postgres@postgresql:5432/postgres
    ports:
      - "8000:8000/tcp"
    links:
      - vecnod
      - postgresql

  vecno_db_filler:
    container_name: vecno_db_filler
    image: supertypo/vecnodb-filler:latest
    restart: unless-stopped
    environment:
      DEBUG: "true"
      VECNOD_HOST_1: vecnod:16110
      SQL_URI: postgresql://postgres:postgres@postgresql:5432/postgres
    links:
      - vecnod
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgresql:/var/lib/postgresql/data/

  vecnod:
    container_name: vecnod
    image: supertypo/vecnod:latest
    restart: unless-stopped
    ports:
      - "16110:16110/tcp"
      - "16111:16111/tcp"
    volumes:
      - vecnod:/app/data/
    command: vecnod --utxoindex --connect=kdxweb.kaspacalc.net

volumes:
  postgresql:
  vecnod:
